# .github/workflows/my-project.yml
name: ModulariedSuperApp

on:
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs:
  build:
    name: test action
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: tuist/tuist-action@0.13.0
        run: tuist fetch
          with:
            command: 'test'
            arguments: ''